name: PullRequest
on: pull_request
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2
    - name: Check minecraft commands
      uses: mcbeet/check-commands@v1.0.6
      with:
        source: .
        minecraft: "1.18"
